# kaldiasr/kaldi:5.4, the oldest possible.
FROM juholeinonen/kaldi-rec-py2@sha256:05bac920478c5b0af17653b96b23dcbaf1f081fc6a9ae88efab423f5cadad44b


# Making kaldi-rec into a kaldi "project".
WORKDIR /opt/kaldi/egs/kaldi-rec/s5

# Need this to create EAF files
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

RUN pip3 install pympi-ling pandas

RUN git clone https://github.com/aalto-speech/finnish-forced-alignment

RUN locale-gen en_US.UTF-8

ENTRYPOINT ["/opt/kaldi/egs/kaldi-rec/s5/finnish-forced-alignment/pipelines/recognize.sh"]
