FROM juholeinonen/kaldi-align@sha256:20056bf9c2af15d4f1a5c9f3567c8aeb23394ee6f01d9a395fb032a6a33ad4de

ENV LANG en_US.UTF-8

WORKDIR /opt/kaldi/egs/align

COPY pipelines/align.sh aligning_with_Docker/bin

ENTRYPOINT ["/opt/kaldi/egs/align/aligning_with_Docker/bin/align.sh"]
